import "./globals.css";
import Navbar from "@/components/Navbar.js";
import "@/stylesheets/detail.css";
import "@/stylesheets/feed.css";
import "./globals.css";
import Footer from "@/components/Footer.js";
import SessionWrapper from "@/components/SessionWrapper";
import NextTopLoader from "nextjs-toploader";
import Script from "next/script";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="afterInteractive"/>
      </head>
      <body
        className={`antialiased`}
      >
        <SessionWrapper>
          <NextTopLoader
          color="#f4c430"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={false}
        />
          <Navbar />
          {children}
          <Footer />
        </SessionWrapper>
      </body>
    </html>
  );
}
